Layouts
POWER-OF-YOUTH/urfu-games-client pull request #13
Opened 2021-11-30 13:05 UTC by Dr-Positive

Adaptive layout and fix card

2021-11-30 13:27 UTC, M1M0G requested changes

2021-11-30 13:27 UTC, M1M0G commented on src/components/Card.jsx
> +className={styles.rating}
clean up

2021-11-30 13:27 UTC, M1M0G commented on src/components/Tags.jsx
> +// import SearchIcon from "@material-ui/icons/Search";
clean up

2021-11-30 13:27 UTC, M1M0G commented on src/components/Tags.jsx
> +                <Competence color="#DB5762" width="100px" competenceName="тег#1">
Давай вынесем в отдельный компонент и будем описание пропом прокидывать, а здесь делать map()

2021-11-30 13:27 UTC, M1M0G commented on src/layouts/PageLayout.module.css
> +/* .gamesGrid
clean up

2021-11-30 13:27 UTC, M1M0G commented on src/pages/GamesPage.jsx
> +                            <GameCard title={game.title} rating={game.rating} img={game.img}/>
Может уже можно подключить все игры? чтобы сразу рендерить через массив?

2021-11-30 13:43 UTC, Aceki requested changes
В целом неплохо, но кое-что нужно поправить.
Слева от названия игры нужен небольшой отступ, а числовое значение рейтинга лучше прижать к правой стороне.
![image](https://user-images.githubusercontent.com/22858278/144058226-db56fe00-007a-4cd4-b21b-c537266c5644.png)

2021-11-30 13:43 UTC, Aceki commented on src/layouts/MainLayout.module.css
> +{
Переноса после селектора быть не должно.
.root {

2021-11-30 13:43 UTC, Aceki commented on src/pages/GamesPage.jsx
> +                            {isMobile ? "Реки" : "Рекомендуемые"}
Реки?
![image](https://user-images.githubusercontent.com/22858278/144057513-e2faaf42-aa75-4983-a96c-36821b5a2dbe.png)

2021-11-30 13:46 UTC, M1M0G commented on src/pages/GamesPage.jsx
> +                            <GameCard title={game.title} rating={game.rating} img={game.img}/>
@Aceki можно уже игры все получать?

2021-11-30 13:57 UTC, Dr-Positive commented on src/layouts/MainLayout.module.css
> +{
flickity это библиотека через которую была сделана эта карусель(слайдер). Пытался сделать свой, но этот лучше по итогу работает.

2021-11-30 14:08 UTC, Aceki commented on src/pages/GamesPage.jsx
> +                            <GameCard title={game.title} rating={game.rating} img={game.img}/>
Да

2021-11-30 14:11 UTC, Aceki commented on src/layouts/MainLayout.module.css
> +{
Понятно. Тогда нужно добавить flickity в package.json. Сейчас его там нет.

2021-12-03 08:45 UTC, Aceki commented
![image](https://user-images.githubusercontent.com/22858278/144572804-0904673f-75cc-4265-b7e8-ca69e7675a84.png)

2021-12-04 15:34 UTC, Aceki requested changes

2021-12-04 15:34 UTC, Aceki commented on package.json
>      "react-dom": "^17.0.2",
Нужно добавить пакет flickity. yarn add flickity

2021-12-04 15:34 UTC, Aceki commented on src/components/Card.jsx
> +const StyledRating = styled(Rating)({
Лучше поместить определение StyledRating после GameCard.

2021-12-04 15:34 UTC, Aceki commented on src/components/Card.jsx
> +import React from "react";
Файл должен называться GameCard.

2021-12-04 15:34 UTC, Aceki commented on src/components/Card.module.css
>  element.style {
Не уверен, что этот кусок кода работает. Он точно здесь нужен?

2021-12-04 15:34 UTC, Aceki commented on src/components/Card.module.css
> +}
Не хватает переносов строки.

2021-12-04 15:34 UTC, Aceki commented on src/components/Tags.jsx
> +import React from "react";
Компонент Tags нужно переименовать в CompetenciesList.

2021-12-07 07:08 UTC, Aceki approved these changes

2021-12-07 07:10 UTC, merged