refactoring/games page
POWER-OF-YOUTH/urfu-games-client pull request #17
Opened 2021-12-08 09:31 UTC by Aceki

Добавлен компоненты MainLayout и Block. Сделан рефакторинг страницы с играми.

2021-12-08 12:58 UTC, M1M0G requested changes

2021-12-08 12:58 UTC, M1M0G commented on src/layouts/MainLayout.jsx
> +            <Header />
Красава!

2021-12-08 12:58 UTC, M1M0G commented on src/models/competence.js
> +                json
для таких штук, есть applySnapshot

2021-12-08 12:58 UTC, M1M0G commented on src/pages/GamePage.jsx
> +    const competencies = useLocalObservable(() => CompetenciesStore.create());
А на главной этот стор не используется?

2021-12-08 12:58 UTC, M1M0G commented on src/pages/GamesPage.jsx
> +        await competencies.load();
ты же их грузишь ещё в начале? Зачем ещё раз?

2021-12-08 13:32 UTC, Aceki commented on src/pages/GamesPage.jsx
> +        await competencies.load();
Нет, компетенции не подгружаются автоматически. Нужно явно вызвать метод load.

2021-12-08 13:36 UTC, Aceki commented on src/models/competence.js
> +                json
У модели Competence есть свойство color, оно относится только к отображению, поэтому с сервера мы его не получаем. При вызове applySnapshot это свойство сбрасывается.

2021-12-08 13:37 UTC, Aceki commented on src/pages/GamePage.jsx
> +    const competencies = useLocalObservable(() => CompetenciesStore.create());
Это хранилище локальное для страницы с игрой.

2021-12-14 13:57 UTC, M1M0G requested changes

2021-12-14 13:57 UTC, M1M0G commented on src/models/competence.js
> +        const _color = observable.box(colors[Math.floor(Math.random() * colors.length)]);
всё же рандом?

2021-12-14 13:57 UTC, M1M0G commented on src/models/competence.js
> +        competencies: types.array(Competence)
почему отказался от мапки?

2021-12-14 13:57 UTC, M1M0G commented on src/models/competence.js
> +            const response = yield competenciesAPI.getCompetence(competenceId);
для чего эта функция
?

2021-12-14 13:57 UTC, M1M0G commented on src/pages/GamesPage.jsx
> +        await Promise.all([
лучше всего, логику унести в саму модель, чтобы отвязать от интерфейса, тут только показывать, а лоадить на afterCreate, и сделать так с каждым стором

2021-12-14 14:30 UTC, merged