Feature/games page/t001
POWER-OF-YOUTH/urfu-games-client pull request #7
Opened 2021-11-11 10:18 UTC by Dr-Positive

Add tegs( Ps: нужно как-то решить проблему с отступами)

2021-11-13 13:31 UTC, Aceki reviewed
Нужно многое поправить и сделать ребейс ветки.
Полезные ссылки:
Документация React  → https://ru.reactjs.org/docs/getting-started.html 
Оформление JSX файлов → https://github.com/airbnb/javascript/tree/master/react

2021-11-13 13:31 UTC, Aceki commented on package.json
> +    "@types/react-dom": "^17.0.11",
Кажется, это здесь лишнее. Этот пакет нужно подключать, если мы используем TypeScript, но у нас JavaScript.

2021-11-13 13:31 UTC, Aceki commented on src/App.jsx
> +import { App as GamesPage } from "./pages/GamesPage";
Должно быть так:
import GamesPage from "./pages/GamesPage"

2021-11-13 13:31 UTC, Aceki commented on src/components/Competence.jsx
> +// const Competence = {
Не нужно оставлять закомментированный код, если он не несёт полезной информации.

2021-11-13 13:31 UTC, Aceki commented on src/components/Slider.jsx
> +// import React, {useState, useEffect} from "react"
Зачем этот файл?

2021-11-13 13:31 UTC, Aceki commented on src/pages/GamesPage.jsx
> +                        {/* ОСТОРОЖНО ТУТ ИДЁТ КАПИПАСТ CARD */}
Карту можно вынести в отдельный компонент.

2021-11-13 13:31 UTC, Aceki commented on src/pages/GamesPage.jsx
> +export function App() {
export default GamesPage() {

2021-11-13 13:31 UTC, Aceki commented on src/pages/PlayPage.jsx
>  import * as React from "react";
PlayPage относится к задаче t006. Здесь её быть не должно.

2021-11-15 07:55 UTC, M1M0G requested changes

2021-11-15 07:55 UTC, M1M0G commented on src/App.jsx
> +// import GamePage from "./pages/GamePage";
remove unused imports

2021-11-15 07:55 UTC, M1M0G commented on src/App.jsx
> +                {/* <Route exact path="/games/:gameId" component={GamePage} /> */}
remove comments

2021-11-15 07:55 UTC, M1M0G commented on src/components/Slider.module.css
> +/* .slider {
remove comments

2021-11-15 07:55 UTC, M1M0G commented on src/components/Competence.module.css
>      padding: 0 10px;
давай заюзаем переменные из стилей

2021-11-15 22:05 UTC, Dr-Positive commented on src/components/Slider.jsx
> +// import React, {useState, useEffect} from "react"
Попытки писать слайдер для card

2021-11-16 08:26 UTC, Aceki requested changes

2021-11-16 08:26 UTC, Aceki commented on src/components/Card.jsx
> +function GameCard({ children }) {
Предполагается, что карточки игр будут иметь разное название, разные значения рейтинга, разные ссылки на игры. Эти параметры нужно передавать через в props'ы.

2021-11-16 08:26 UTC, Aceki commented on src/components/Dialog.module.css
> +.css-1e6y48t-MuiButtonBase-root-MuiButton-root
Странное называние у стиля. Это точно работает?

2021-11-16 08:26 UTC, Aceki commented on src/pages/GamesPage.jsx
> +                        <Popup title="Системная аналитика" tegs="тег#1">
У нас не теги, а компетенции.

2021-11-16 08:26 UTC, Aceki commented on src/pages/GamesPage.module.css
> +.logotip {
Не стоит писать русские слова латиницей. Если этот класс относится к логотипу лучше назвать его logo.

2021-11-17 11:59 UTC, Aceki approved these changes
Нужно исправить оставшиеся замечания и можно заливать.

2021-11-17 11:59 UTC, Aceki commented on src/components/Slider.module.css
> +    position: relative;
Не исправлено.

2021-11-17 11:59 UTC, Aceki commented on src/components/Slider.jsx
> +// import slide1 from "../img/slide1.jpg"
Если это не используется, то нужно удалить.

2021-11-17 19:57 UTC, merged